name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Maven & JDK 11
      uses: xlui/action-maven-cli@v1.1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
